/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author Soumya
 */
public enum CSGManagerProp {
    
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE COURSE WORKSPACE CONTROLS
    COURSE_INFO_HEADER_TEXT,
    SUBJECT_TEXT,
    CSE_TEXT,
    ISE_TEXT,
    ECE_TEXT,
    NUMBER_TEXT,
    TEXT_219,
    TEXT_308,
    TEXT_373,
    TEXT_2016,
    TEXT_2017,
    TEXT_2018,
    SEMESTER_TEXT,
    FALL_TEXT,
    SPRING_TEXT,
    YEAR_TEXT,
    TITLE_TEXT,
    NAME_TEXT,
    HOME_TEXT,
    CHANGE_TEXT,
    EXPORT_TEXT,
    EXPORT_DIR_TEXT,
    DIR_HEADER_TEXT,
    DIR_INFO_TEXT,
    TEMPLATE_BUTTON_TEXT,
    PAGES_TEXT,
    USE_COLUMN_TEXT,
    NAVBAR_COLUMN_TEXT,
    FILE_COLUMN_TEXT,
    SCRIPT_COLUMN_TEXT,
    STYLE_TEXT,
    BANNER_TEXT,
    LEFT_FOOTER_TEXT,
    RIGHT_FOOTER_TEXT,
    STYLESHEET_TEXT,
    STYLESHEET_NOTE_TEXT, 
    COURSE_TAB_TEXT,
    
      // THESE ARE FOR TEXT PARTICULAR TO THE TA WORKSPACE CONTROLS
    TA_TAB_TEXT,
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    START_TIME_TEXT,
    END_TIME_TEXT,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE TA Workspace
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    TA_EMAIL_INVALID,
    TA_EMAIL_INVALID_MESSAGE,
    START_END_TIME_ERROR,
    START_END_TIME_ERROR_MESSAGE, 
    
    //THESE ARE TEXT PARTICULAR TO THE RECITATION WORKSPACE
    RECITATION_HEADER_TEXT, 
    SECTION_COLUMN_TEXT, 
    INSTRUCTOR_COLUMN_TEXT, 
    DAY_COLUMN_TEXT, 
    LOCATION_COLUMN_TEXT, 
    TA1_COLUMN_TEXT, 
    TA2_COLUMN_TEXT, 
    
    ADD_EDIT_TEXT, SECTION_TEXT,
    
}


