/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author Soumya
 */
public enum CSGManagerProp {
    
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE COURSE WORKSPACE CONTROLS
    COURSE_INFO_HEADER_TEXT,
    SUBJECT_TEXT,
    CSE_TEXT,
    ISE_TEXT,
    ECE_TEXT,
    NUMBER_TEXT,
    TEXT_219,
    TEXT_308,
    TEXT_373,
    TEXT_2016,
    TEXT_2017,
    TEXT_2018,
    SEMESTER_TEXT,
    FALL_TEXT,
    SPRING_TEXT,
    YEAR_TEXT,
    TITLE_TEXT,
    NAME_TEXT,
    HOME_TEXT,
    CHANGE_TEXT,
    EXPORT_TEXT,
    EXPORT_DIR_TEXT,
    DIR_HEADER_TEXT,
    DIR_INFO_TEXT,
    TEMPLATE_BUTTON_TEXT,
    PAGES_TEXT,
    USE_COLUMN_TEXT,
    NAVBAR_COLUMN_TEXT,
    FILE_COLUMN_TEXT,
    SCRIPT_COLUMN_TEXT,
    STYLE_TEXT,
    BANNER_TEXT,
    LEFT_FOOTER_TEXT,
    RIGHT_FOOTER_TEXT,
    STYLESHEET_TEXT,
    STYLESHEET_NOTE_TEXT, 
    COURSE_TAB_TEXT,
    
      // THESE ARE FOR TEXT PARTICULAR TO THE TA WORKSPACE CONTROLS
    TA_TAB_TEXT,
    TAS_HEADER_TEXT,
    NAME_COLUMN_TEXT,
    EMAIL_COLUMN_TEXT,
    NAME_PROMPT_TEXT,
    EMAIL_PROMPT_TEXT,
    ADD_BUTTON_TEXT,
    CLEAR_BUTTON_TEXT,
    UPDATE_BUTTON_TEXT,
    OFFICE_HOURS_SUBHEADER,
    START_TIME_TEXT,
    END_TIME_TEXT,
    OFFICE_HOURS_TABLE_HEADERS,
    DAYS_OF_WEEK,
    UNDERGRAD_COLUMN_TEXT,
    
    // THESE ARE FOR ERROR MESSAGES PARTICULAR TO THE TA Workspace
    MISSING_TA_NAME_TITLE,
    MISSING_TA_NAME_MESSAGE,
    MISSING_TA_EMAIL_TITLE,
    MISSING_TA_EMAIL_MESSAGE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_TITLE,
    TA_NAME_AND_EMAIL_NOT_UNIQUE_MESSAGE,
    TA_EMAIL_INVALID,
    TA_EMAIL_INVALID_MESSAGE,
    START_END_TIME_ERROR,
    START_END_TIME_ERROR_MESSAGE, 
    
    //THESE ARE TEXT PARTICULAR TO THE RECITATION WORKSPACE
    RECITATION_HEADER_TEXT, 
    SECTION_COLUMN_TEXT, 
    INSTRUCTOR_COLUMN_TEXT, 
    DAY_COLUMN_TEXT, 
    LOCATION_COLUMN_TEXT, 
    TA1_COLUMN_TEXT, 
    TA2_COLUMN_TEXT, 
    
    ADD_EDIT_TEXT, 
    SECTION_TEXT, 
    RECITATION_TAB_TEXT, 
    CLEAR_TEXT, 
    ADD_TEXT, 
    TA2_TEXT, 
    TA1_TEXT, 
    LOCATION_TEXT, 
    DAY_TEXT, 
    INSTRUCTOR_TEXT, 
    
    
    //THESE ARE TEXT PARTICULAR TO THE SCHEDULE WORKSPACE
    SCHEDULE_HEADER_TEXT, 
    CALENDAR_TEXT, 
    START_DAY_TEXT, 
    END_DAY_TEXT, 
    ITEMS_TEXT, 
    TYPE_COLUMN_TEXT, 
    DATE_COLUMN_TEXT, 
    TITLE_COLUMN_TEXT, 
    TOPIC_COLUMN_TEXT, 
    CRITERIA_TEXT, 
    LINK_TEXT, 
    TOPIC_TEXT, 
    TIME_TEXT, 
    DATE_TEXT, 
    HW_TEXT, 
    LECTURE_TEXT, 
    HOLIDAY_TEXT, 
    TYPE_TEXT, 
    SCHEDULE_TAB_TEXT, 
    
    //THESE ARE TEXT PARTICULAR TO THE PROJECT WORKSPACE
    PROJECT_HEADER_TEXT, 
    TEAM_TEXT, 
    COLOR_COLUMN_TEXT, 
    TEXT_COLOR_COLUMN_TEXT, 
    LINK_COLUMN_TEXT, 
    COLOR_TEXT, 
    TEXT_COLOR_TEXT, 
    HYPERLINK_TEXT, 
    STUDENT_TEXT, 
    FIRSTNAME_COLUMN_TEXT, 
    TEAM_COLUMN_TEXT, 
    LASTNAME_COLUMN_TEXT, 
    ROLE_COLUMN_TEXT, 
    FIRSTNAME_TEXT, 
    LASTNAME_TEXT,
    TEAM_COMOBO_TEXT, 
    ROLE_TEXT, 
    PROJECT_TAB_TEXT, 
    STUDENT_NAME_TEXT, 
    
    //THESE ARE TEXT PARTICULAR TO THE COURSE DATA
    COURSE_HOME_TEXT, 
    SYLLABUS_TEXT, 
    SCHEDULE_TEXT, 
    HWS_TEXT, 
    PROJECTS_TEXT, 
    
}


